export const HolidayCabinDetails = [
    {
        cabinTitle: 'One Bedroom Holiday Villa',
        guests: '10',
        bedrooms: '1',
        bathrooms: '1',
        detailsPage: 'one-bedroom-holiday-villa',
        thumbnail: 'one-bedroom-holiday-villa-thumbnail',
    },
    {
        cabinTitle: 'Two Bedroom Holiday Villa',
        guests: '6',
        bedrooms: '2',
        bathrooms: '1',
        detailsPage: 'two-bedroom-holiday-villa',
        thumbnail: 'two-bedroom-holiday-villa-thumbnail',
    },
    {
        cabinTitle: 'Three Bedroom Holiday Villa',
        guests: '6',
        bedrooms: '3',
        bathrooms: '1',
        detailsPage: 'three-bedroom-holiday-villa',
        thumbnail: 'three-bedroom-holiday-villa-thumbnail',
    },
    {
        cabinTitle: 'One Bedroom Resort Home',
        guests: '2',
        bedrooms: '1',
        bathrooms: '1',
        detailsPage: 'one-bedroom-resort-home',
        thumbnail: 'one-bedroom-resort-home-thumbnail',
    },
    {
        cabinTitle: 'Two Bedroom Holiday Home',
        guests: '4',
        bedrooms: '2',
        bathrooms: '1',
        detailsPage: 'two-bedroom-holiday-home',
        thumbnail: 'two-bedroom-holiday-home-thumbnail',
    },
    {
        cabinTitle: 'Two Bedroom Resort Home',
        guests: '4',
        bedrooms: '2',
        bathrooms: '1',
        detailsPage: 'two-bedroom-resort-home',
        thumbnail: 'two-bedroom-resort-home-thumbnail',
    },
    {
        cabinTitle: 'Three Bedroom Holiday Home',
        guests: '6',
        bedrooms: '3',
        bathrooms: '2',
        detailsPage: 'three-bedroom-holiday-home',
        thumbnail: 'three-bedroom-holiday-home-thumbnail',
    },
    {
        cabinTitle: 'Three Bedroom Resort Home',
        guests: '6',
        bedrooms: '3',
        bathrooms: '1',
        detailsPage: 'three-bedroom-resort-home',
        thumbnail: 'three-bedroom-resort-home-thumbnail',
    },
    {
        cabinTitle: 'Large Family Holiday Home',
        guests: '8',
        bedrooms: '3',
        bathrooms: '2',
        detailsPage: 'large-family-holiday-home',
        thumbnail: 'large-family-holiday-home-thumbnail',
    },
]