export const HolidayCabinSliderImages = [
    {
        cabinTitle: 'one-bedroom-holiday-villa',
        cabinDescription: 'A queen master bedroom plus two lengthy bunk beds off the living area provides a very versatile cabin for one to four guests. All villas offer great value and functionality including a kitchen and all the self-contained essentials. They feature high ceilings with comfortable indoor living spaces and a glass door opening to a sheltered alfresco patio.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x1',
            'Beds – Queen x1',
            'Beds – Single Bunk x2',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'one-bedroom-holiday-villa',
            'one-bedroom-holiday-villa-master-bedroom',
            'one-bedroom-holiday-villa-kitchen',
            'one-bedroom-holiday-villa-bathroom',
            'one-bedroom-holiday-villa-bunks',
        ]
    },
    {
        cabinTitle: 'two-bedroom-holiday-villa',
        cabinDescription: 'A queen master bedroom with two lengthy bunk beds in a separate bunk room plus two more lengthy bunk beds off the living area enable suitable sleeping capacity for up to six guests. All villas offer great value and functionality including a kitchen and all the self-contained essentials. They feature high ceilings with comfortable indoor living spaces and a glass door opening to a sheltered alfresco patio.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x2',
            'Beds – Queen x1',
            'Beds – Single Bunk x4',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'two-bedroom-holiday-villa',
            'two-bedroom-holiday-villa-master-bedroom',
            'two-bedroom-holiday-villa-bathroom',
            'two-bedroom-holiday-villa-bedroom-2',
        ]
    },
    {
        cabinTitle: 'three-bedroom-holiday-villa',
        cabinDescription: 'A queen master bedroom plus two lengthy bunk beds off the living area provides a very versatile cabin for one to four guests. All villas offer great value and functionality including a kitchen and all the self-contained essentials. They feature high ceilings with comfortable indoor living spaces and a glass door opening to a sheltered alfresco patio.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x3',
            'Beds – Queen x1',
            'Beds – Single x2',
            'Beds – Single Bunk x2',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'three-bedroom-holiday-villa',
            'three-bedroom-holiday-villa-master-bedroom',
            'three-bedroom-holiday-villa-kitchen',
            'three-bedroom-holiday-villa-bathroom',
            'three-bedroom-holiday-villa-bedroom-2',
        ]
    },
    {
        cabinTitle: 'one-bedroom-resort-home',
        cabinDescription: 'Queen master with ensuite, kitchen, dining and lounge areas. A very attractive retreat for singles and couples with the additional convenience of a laundry with washing machine, a dishwasher and private undercover carport parking beside cabin.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x1',
            'Beds – Queen x1',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'one-bedroom-resort-home-living-room',
            'one-bedroom-resort-home-kitchen',
            'one-bedroom-resort-home-master-bedroom',
            'one-bedroom-resort-home-bathroom',
            'one-bedroom-resort-home-cabin',
        ]
    },
    {
        cabinTitle: 'two-bedroom-holiday-home',
        cabinDescription: 'Accommodation for up to four people in comfort and style. A Queen master bedroom and second bedroom with two single beds. A relaxing lounge setting with dining area and a comprehensive kitchen with dishwasher will make you feel right at home. A bathroom with separate toilet and a laundry with washing machine adds further convenience.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x2',
            'Beds – Queen x1',
            'Beds – Single x2',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'two-bedroom-holiday-home',
            'two-bedroom-holiday-home-master-bedroom',
            'two-bedroom-holiday-home-kitchen',
            'two-bedroom-holiday-home-bedroom-2',
            'two-bedroom-holiday-bathroom',
        ]
    },
    {
        cabinTitle: 'two-bedroom-resort-home',
        cabinDescription: 'Spacious cabins which offer a high level of privacy and comfort for up to four guests with a queen bed in the main bedroom and two singles beds in second bedroom. These cabins are nestled in quieter areas of the resort and have the additional advantage of a carport for undercover parking making them very popular for guests staying for longer visits.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x2',
            'Beds – Queen x1',
            'Beds – Single x2',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Parking (Covered x1)',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'two-bedroom-resort-home',
            'two-bedroom-resort-home-kitchen',
            'two-bedroom-resort-home-master-bedroom',
            'two-bedroom-resort-bathroom',
            'two-bedroom-resort-bedroom-2',
            'two-bedroom-resort-cabin',
            'two-bedroom-resort-laundry',
        ]
    },
    {
        cabinTitle: 'three-bedroom-holiday-home',
        cabinDescription: 'The largest in the villa range, offering great privacy and comfort for up to six guests. They have a queen master bedroom and a selection of two other bedrooms, one with two single beds and the other with two lengthy bunk beds. This villa also has a larger kitchen with a dishwasher. All villas offer great value and functionality including a kitchen and all the self-contained essentials. They feature high ceilings with comfortable indoor living spaces and a glass door opening to a sheltered alfresco patio.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x3',
            'Beds – Queen x1',
            'Beds – Single x2',
            'Beds – Single Bunk x2',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Washing Machine',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'three-bedroom-holiday-home',
            'three-bedroom-holiday-home-kitchen',
            'three-bedroom-holiday-home-master-bedroom',
            'three-bedroom-holiday-home-ensuite',
            'three-bedroom-holiday-home-bedroom-2',
            'three-bedroom-holiday-home-bathroom',
            'three-bedroom-holiday-home-bedroom-3',
            'three-bedroom-holiday-home-patio',
        ]
    },
    {
        cabinTitle: 'three-bedroom-resort-home',
        cabinDescription: 'Excellent cabins for up to six people with a queen master bedroom, second and third bedrooms each with two single beds. Relaxing lounge setting, Larger kitchen with dishwasher, your own laundry with washing machine and outside clothesline, separate bathroom and toilet with the additional advantage of a carport for undercover parking.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x1',
            'Bedrooms x3',
            'Beds – Queen x1',
            'Beds – Single x4',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Washing Machine',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Laundry Tub',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking (Covered) x2',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'three-bedroom-resort-home',
            'three-bedroom-resort-home-kitchen',
            'three-bedroom-resort-home-master-bedroom',
            'three-bedroom-resort-home-bathroom',
            'three-bedroom-resort-home-bedroom-2',
            'three-bedroom-resort-home-cabin',
            'three-bedroom-resort-home-laundry',
        ]
    },
    {
        cabinTitle: 'large-family-holiday-home',
        cabinDescription: 'Designed with larger families in mind this cabin will sleep up to eight people. The queen master bedroom has an ensuite bathroom, the second bedroom has two single beds and bedroom three has two bunk beds. A second set of bunk beds are located in an alcove off the living area which has a large corner lounge, television and dining area.',
        featureList: [
            'Air Conditioning',
            'Balcony',
            'Bathrooms x2',
            'Bedrooms x3',
            'Beds – Queen x1',
            'Beds – Single x2',
            'Beds – Single Bunk x4',
            'Clock Radio',
            'Cook Top (4 Hot Plates)',
            'Dining Area',
            'Dishwasher',
            'Washing Machine',
            'Fan',
            'Free Wi-Fi',
            'Full Kitchen',
            'Guest Toiletries',
            'Hair Dryer',
            'Heating',
            'Iron & Ironing Board',
            'Laundry Tub',
            'Linen Provided',
            'Lounge Room',
            'Microwave',
            'Oven',
            'Parking',
            'Tea & Coffee',
            'TV x1'],
        images: [
            'large-family-holiday-home',
            'large-family-holiday-home-kitchen',
            'large-family-holiday-home-master-bedroom',
            'large-family-holiday-ensuite',
            'large-family-holiday-home-bedroom-2',
            'large-family-holiday-home-bathroom',
            'large-family-holiday-home-bedroom-3',
        ]
    },



];