export const FeatureSelection = [
  "Non-Smoking",
  "Outdoor clothesline",
  "Outdoor setting",
  "BBQ facilities onsite",
  "Garden maintenance",
  "No pets allowed",
  "Air-conditioning",
  "Bedside cabinets",
  "Covered parking (carport)",
  "Dining room setting",
  "Electric oven & hotplates",
  "Ensemble queen bed x 1",
  "Ensemble single bed x 1",
  "Family-size refrigerator",
  "Flyscreens",
  "Kitchen with appliances",
  "Lounge suite",
  "Playground on-site",
  "Security screen door",
  "Swimming pool onsite",
  "Television set",
  "Tennis court onsite",
  "Utilities connected",
  "Veranda",
  "Wardrobes (built-in)",
  "Washing machine",
];
